name: Build Flutter APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.5'

      - name: Get dependencies
        run: flutter pub get --verbose
        working-directory: offline_vault_kyc

      - name: Build APK
        run: flutter build apk --release
        working-directory: offline_vault_kyc

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: offline_vault_kyc/build/app/outputs/flutter-apk/app-release.apk
